version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8077:80'
    environment:
    # - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - '5506:3306'
    restart: unless-stopped
    environment:
        MYSQL_PASSWORD: 12345678
        MYSQL_ROOT_PASSWORD: 12345678